theme: jekyll-theme-cayman
title: Pier Paolo Ippolito
name: Pier Paolo Ippolito
author: Pier Paolo Ippolito
description: Software Engineer - MEng Electronic Engineering with Artificial Intelligence - University of Southampton

avatar: https://cdn-images-1.medium.com/fit/c/80/80/0*juYh9_bVEJB6Q18x.jpg

permalink: /blog/

paginate: 4
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-seo-tag
  
plugins: [jekyll-paginate]
