theme: jekyll-theme-hacker
title: Pier Paolo Ippolito
name: Pier Paolo Ippolito
author: Pier Paolo Ippolito
description: Software Engineer - MEng Electronic Engineering with Artificial Intelligence - University of Southampton

permalink: /blog/
